const actions = {
  AUTH: 'AUTH',
  USER: 'USER',
  NOTES: 'NOTES',
  CURRENT_NOTE: 'CURRENT_NOTE',
  SETTINGS: 'SETTINGS',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  FOLDERS: 'FOLDERS',
  LOGOUT_MODAL: 'LOGOUT_MODAL',
  ABOUT_MODAL: 'ABOUT_MODAL',
  TOAST: 'TOAST',
  PROMPT: 'PROMPT',
  WINDOW_INNER_SIZE: 'WINDOW_INNER_SIZE',
  PROPERTIES_DRAWER: 'PROPERTIES_DRAWER',
  QUERY_NOTES: 'QUERY_NOTES',
  NAVIGATION_DRAWER: 'NAVIGATION_DRAWER',
  EDITOR_TOOLS_TOGGLER_MODAL: 'EDITOR_TOOLS_TOGGLER_MODAL'
};

export default actions;
